"""add task_navigation_snapshot table

Revision ID: d98926e63d38
Revises: 52f3e86566bf
Create Date: 2026-03-01 14:55:11.294933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd98926e63d38'
down_revision = '52f3e86566bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_navigation_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_instance_id', sa.Integer(), nullable=False),
    sa.Column('task_definition_id_path', sa.String(length=255), nullable=False),
    sa.Column('json_data_hash', sa.String(length=255), nullable=False),
    sa.Column('navigation_sequence', sa.Integer(), nullable=False),
    sa.Column('task_guid', sa.String(length=50), nullable=False),
    sa.Column('bpmn_identifier', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['process_instance_id'], ['process_instance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_navigation_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_navigation_snapshot_json_data_hash'), ['json_data_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_navigation_snapshot_process_instance_id'), ['process_instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_navigation_snapshot_task_definition_id_path'), ['task_definition_id_path'], unique=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('guid'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('guid'), ['guid'])

    with op.batch_alter_table('task_navigation_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_navigation_snapshot_task_definition_id_path'))
        batch_op.drop_index(batch_op.f('ix_task_navigation_snapshot_process_instance_id'))
        batch_op.drop_index(batch_op.f('ix_task_navigation_snapshot_json_data_hash'))

    op.drop_table('task_navigation_snapshot')
    # ### end Alembic commands ###
